export const getStudentsByProfessorDNI: any = {
  43222224: [
    {
      studentDNI: 42111111,
      studentName: "Leandro",
      studentLastName: "Paredes",
      classroomName: "Aula 1.1",
      schedulerDay: "Lunes",
      schedulerStartTime: "08:30",
      schedulerEndTime: "10:00",
      subjectName: "Matematica",
      subjectCode: 1,
    },
    {
      studentDNI: 42111112,
      studentName: "Enzo",
      studentLastName: "Ferrari",
      // classroomName: "Aula 1.2",
      // schedulerDay: "Lunes",
      // schedulerStartTime: "10:30",
      // schedulerEndTime: "12:00",
      subjectName: "Matematica",
      subjectCode: 1,
    },
    {
      studentDNI: 42111113,
      studentName: "Ben",
      studentLastName: "Tenisson",
      // classroomName: "Aula 2.1",
      // schedulerDay: "Lunes",
      // schedulerStartTime: "13:45",
      // schedulerEndTime: "15:15",
      subjectName: "Matematica",
      subjectCode: 1,
    },
    {
      studentDNI: 42111114,
      studentName: "Marcos",
      studentLastName: "Herrera",
      classroomName: "Aula 2.2",
      schedulerDay: "Martes",
      schedulerStartTime: "09:15",
      schedulerEndTime: "10:45",
      subjectName: "Matematica",
      subjectCode: 1,
    },
    {
      studentDNI: 42111115,
      studentName: "Diego",
      studentLastName: "Barrios",
      classroomName: "Aula 3.1",
      schedulerDay: "Martes",
      schedulerStartTime: "11:30",
      schedulerEndTime: "13:00",
      subjectName: "Programacion I",
      subjectCode: 3,
    },
    {
      studentDNI: 42111116,
      studentName: "Miguel",
      studentLastName: "Pretan",
      classroomName: "Aula 3.2",
      schedulerDay: "Martes",
      schedulerStartTime: "14:20",
      schedulerEndTime: "15:50",
      subjectName: "Programacion I",
      subjectCode: 3,
    },
    {
      studentDNI: 42111117,
      studentName: "Pedro",
      studentLastName: "Porro",
      classroomName: "Aula 4.1",
      schedulerDay: "Miércoles",
      schedulerStartTime: "08:45",
      schedulerEndTime: "10:15",
      subjectName: "Programacion I",
      subjectCode: 3,
    },
    {
      studentDNI: 43111128,
      studentName: "Jack",
      studentLastName: "Black",
      // classroomName: "Aula 1.1",
      // schedulerDay: "Lunes",
      // schedulerStartTime: "08:30",
      // schedulerEndTime: "10:00",
      subjectName: "Fisica I",
      subjectCode: 2,
    },
    {
      studentDNI: 43111129,
      studentName: "Brad",
      studentLastName: "Pity",
      // classroomName: "Aula 1.2",
      // schedulerDay: "Lunes",
      // schedulerStartTime: "10:30",
      // schedulerEndTime: "12:00",
      subjectName: "Fisica I",
      subjectCode: 2,
    },
    {
      studentDNI: 43111130,
      studentName: "Lucas",
      studentLastName: "larreta",
      classroomName: "Aula 2.1",
      schedulerDay: "Lunes",
      schedulerStartTime: "13:45",
      schedulerEndTime: "15:15",
      subjectName: "Fisica I",
      subjectCode: 2,
    },
    {
      studentDNI: 43111131,
      studentName: "Leito",
      studentLastName: "Rua",
      classroomName: "Aula 2.2",
      schedulerDay: "Martes",
      schedulerStartTime: "09:15",
      schedulerEndTime: "10:45",
      subjectName: "Fisica I",
      subjectCode: 2,
    },
    {
      studentDNI: 43111132,
      studentName: "Victor",
      studentLastName: "viela",
      classroomName: "Aula 3.1",
      schedulerDay: "Martes",
      schedulerStartTime: "11:30",
      schedulerEndTime: "13:00",
      subjectName: "Fisica I",
      subjectCode: 2,
    },
    {
      studentDNI: 43111133,
      studentName: "Ramiro",
      studentLastName: "Guerrera",
      classroomName: "Aula 3.2",
      schedulerDay: "Martes",
      schedulerStartTime: "14:20",
      schedulerEndTime: "15:50",
      subjectName: "Programacion I",
      subjectCode: 3,
    },
    {
      studentDNI: 43111134,
      studentName: "Maxi",
      studentLastName: "Insfran",
      classroomName: "Aula 4.1",
      schedulerDay: "Miércoles",
      schedulerStartTime: "08:45",
      schedulerEndTime: "10:15",
      subjectName: "Programacion I",
      subjectCode: 3,
    },
  ],
  43111110: [
    {
      studentDNI: 42111111,
      studentName: "Leandro",
      studentLastName: "Paredes",
      // classroomName: "Aula 1.1",
      // schedulerDay: "Lunes",
      // schedulerStartTime: "08:30",
      // schedulerEndTime: "10:00",
      subjectName: "Metodologia de Sistemas",
      subjectCode: 5,
    },
    {
      studentDNI: 42111112,
      studentName: "Enzo",
      studentLastName: "Ferrari",
      classroomName: "Aula 1.2",
      schedulerDay: "Lunes",
      schedulerStartTime: "10:30",
      schedulerEndTime: "12:00",
      subjectName: "Metodologia de Sistemas",
      subjectCode: 5,
    },
    {
      studentDNI: 42111113,
      studentName: "Ben",
      studentLastName: "Tenisson",
      classroomName: "Aula 2.1",
      schedulerDay: "Lunes",
      schedulerStartTime: "13:45",
      schedulerEndTime: "15:15",
      subjectName: "Metodologia de Sistemas",
      subjectCode: 5,
    },
    {
      studentDNI: 42111114,
      studentName: "Marcos",
      studentLastName: "Herrera",
      // classroomName: "Aula 2.2",
      // schedulerDay: "Martes",
      // schedulerStartTime: "09:15",
      // schedulerEndTime: "10:45",
      subjectName: "Metodologia de Sistemas",
      subjectCode: 5,
    },
    {
      studentDNI: 42111115,
      studentName: "Diego",
      studentLastName: "Barrios",
      // classroomName: "Aula 3.1",
      // schedulerDay: "Martes",
      // schedulerStartTime: "11:30",
      // schedulerEndTime: "13:00",
      // subjectName: "Programacion II",
      subjectCode: 6,
    },
    {
      studentDNI: 42111116,
      studentName: "Miguel",
      studentLastName: "Pretan",
      classroomName: "Aula 3.2",
      schedulerDay: "Martes",
      schedulerStartTime: "14:20",
      schedulerEndTime: "15:50",
      subjectName: "Programacion II",
      subjectCode: 6,
    },
    {
      studentDNI: 42111117,
      studentName: "Pedro",
      studentLastName: "Porro",
      classroomName: "Aula 4.1",
      schedulerDay: "Miércoles",
      schedulerStartTime: "08:45",
      schedulerEndTime: "10:15",
      subjectName: "Programacion II",
      subjectCode: 6,
    },
    {
      studentDNI: 43111128,
      studentName: "Jack",
      studentLastName: "Black",
      classroomName: "Aula 1.1",
      schedulerDay: "Lunes",
      schedulerStartTime: "08:30",
      schedulerEndTime: "10:00",
      subjectName: "Programacion II",
      subjectCode: 6,
    },
    {
      studentDNI: 43111129,
      studentName: "Brad",
      studentLastName: "Pity",
      classroomName: "Aula 1.2",
      schedulerDay: "Lunes",
      schedulerStartTime: "10:30",
      schedulerEndTime: "12:00",
      subjectName: "Ingles",
      subjectCode: 7,
    },
    {
      studentDNI: 43111130,
      studentName: "Lucas",
      studentLastName: "larreta",
      // classroomName: "Aula 2.1",
      // schedulerDay: "Lunes",
      // schedulerStartTime: "13:45",
      // schedulerEndTime: "15:15",
      subjectName: "Ingles",
      subjectCode: 7,
    },
    {
      studentDNI: 43111131,
      studentName: "Leito",
      studentLastName: "Rua",
      // classroomName: "Aula 2.2",
      // schedulerDay: "Martes",
      // schedulerStartTime: "09:15",
      // schedulerEndTime: "10:45",
      subjectName: "Ingles",
      subjectCode: 7,
    },
    {
      studentDNI: 43111132,
      studentName: "Victor",
      studentLastName: "viela",
      classroomName: "Aula 3.1",
      schedulerDay: "Martes",
      schedulerStartTime: "11:30",
      schedulerEndTime: "13:00",
      subjectName: "Ingles",
      subjectCode: 7,
    },
    {
      studentDNI: 43111133,
      studentName: "Ramiro",
      studentLastName: "Guerrera",
      classroomName: "Aula 3.2",
      schedulerDay: "Martes",
      schedulerStartTime: "14:20",
      schedulerEndTime: "15:50",
      subjectName: "Ingles",
      subjectCode: 7,
    },
    {
      studentDNI: 43111134,
      studentName: "Maxi",
      studentLastName: "Insfran",
      classroomName: "Aula 4.1",
      schedulerDay: "Miércoles",
      schedulerStartTime: "08:45",
      schedulerEndTime: "10:15",
      subjectName: "Ingles",
      subjectCode: 7,
    },
  ],
};
